// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: trade_core.proto

package trade_core

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TradeCoreServiceClient is the client API for TradeCoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TradeCoreServiceClient interface {
	Recharge(ctx context.Context, in *RechargeRequest, opts ...grpc.CallOption) (*RechargeResponse, error)
	Order(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error)
	OrderList(ctx context.Context, in *OrderListRequest, opts ...grpc.CallOption) (*OrderListResponse, error)
}

type tradeCoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTradeCoreServiceClient(cc grpc.ClientConnInterface) TradeCoreServiceClient {
	return &tradeCoreServiceClient{cc}
}

func (c *tradeCoreServiceClient) Recharge(ctx context.Context, in *RechargeRequest, opts ...grpc.CallOption) (*RechargeResponse, error) {
	out := new(RechargeResponse)
	err := c.cc.Invoke(ctx, "/jlu_cow_studio.trade_core.TradeCoreService/Recharge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeCoreServiceClient) Order(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error) {
	out := new(OrderResponse)
	err := c.cc.Invoke(ctx, "/jlu_cow_studio.trade_core.TradeCoreService/Order", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeCoreServiceClient) OrderList(ctx context.Context, in *OrderListRequest, opts ...grpc.CallOption) (*OrderListResponse, error) {
	out := new(OrderListResponse)
	err := c.cc.Invoke(ctx, "/jlu_cow_studio.trade_core.TradeCoreService/OrderList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradeCoreServiceServer is the server API for TradeCoreService service.
// All implementations must embed UnimplementedTradeCoreServiceServer
// for forward compatibility
type TradeCoreServiceServer interface {
	Recharge(context.Context, *RechargeRequest) (*RechargeResponse, error)
	Order(context.Context, *OrderRequest) (*OrderResponse, error)
	OrderList(context.Context, *OrderListRequest) (*OrderListResponse, error)
	mustEmbedUnimplementedTradeCoreServiceServer()
}

// UnimplementedTradeCoreServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTradeCoreServiceServer struct {
}

func (UnimplementedTradeCoreServiceServer) Recharge(context.Context, *RechargeRequest) (*RechargeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Recharge not implemented")
}
func (UnimplementedTradeCoreServiceServer) Order(context.Context, *OrderRequest) (*OrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Order not implemented")
}
func (UnimplementedTradeCoreServiceServer) OrderList(context.Context, *OrderListRequest) (*OrderListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderList not implemented")
}
func (UnimplementedTradeCoreServiceServer) mustEmbedUnimplementedTradeCoreServiceServer() {}

// UnsafeTradeCoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradeCoreServiceServer will
// result in compilation errors.
type UnsafeTradeCoreServiceServer interface {
	mustEmbedUnimplementedTradeCoreServiceServer()
}

func RegisterTradeCoreServiceServer(s grpc.ServiceRegistrar, srv TradeCoreServiceServer) {
	s.RegisterService(&TradeCoreService_ServiceDesc, srv)
}

func _TradeCoreService_Recharge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RechargeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeCoreServiceServer).Recharge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jlu_cow_studio.trade_core.TradeCoreService/Recharge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeCoreServiceServer).Recharge(ctx, req.(*RechargeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeCoreService_Order_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeCoreServiceServer).Order(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jlu_cow_studio.trade_core.TradeCoreService/Order",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeCoreServiceServer).Order(ctx, req.(*OrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeCoreService_OrderList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeCoreServiceServer).OrderList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jlu_cow_studio.trade_core.TradeCoreService/OrderList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeCoreServiceServer).OrderList(ctx, req.(*OrderListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TradeCoreService_ServiceDesc is the grpc.ServiceDesc for TradeCoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TradeCoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jlu_cow_studio.trade_core.TradeCoreService",
	HandlerType: (*TradeCoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Recharge",
			Handler:    _TradeCoreService_Recharge_Handler,
		},
		{
			MethodName: "Order",
			Handler:    _TradeCoreService_Order_Handler,
		},
		{
			MethodName: "OrderList",
			Handler:    _TradeCoreService_OrderList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trade_core.proto",
}
