// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: pack.proto

package pack

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserCoreServiceClient is the client API for UserCoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserCoreServiceClient interface {
	// 用户登录方法
	PackItems(ctx context.Context, in *PackItemsReq, opts ...grpc.CallOption) (*PackItemsRes, error)
}

type userCoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserCoreServiceClient(cc grpc.ClientConnInterface) UserCoreServiceClient {
	return &userCoreServiceClient{cc}
}

func (c *userCoreServiceClient) PackItems(ctx context.Context, in *PackItemsReq, opts ...grpc.CallOption) (*PackItemsRes, error) {
	out := new(PackItemsRes)
	err := c.cc.Invoke(ctx, "/jlu_cow_studio.pack.UserCoreService/PackItems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserCoreServiceServer is the server API for UserCoreService service.
// All implementations must embed UnimplementedUserCoreServiceServer
// for forward compatibility
type UserCoreServiceServer interface {
	// 用户登录方法
	PackItems(context.Context, *PackItemsReq) (*PackItemsRes, error)
	mustEmbedUnimplementedUserCoreServiceServer()
}

// UnimplementedUserCoreServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserCoreServiceServer struct {
}

func (UnimplementedUserCoreServiceServer) PackItems(context.Context, *PackItemsReq) (*PackItemsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PackItems not implemented")
}
func (UnimplementedUserCoreServiceServer) mustEmbedUnimplementedUserCoreServiceServer() {}

// UnsafeUserCoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserCoreServiceServer will
// result in compilation errors.
type UnsafeUserCoreServiceServer interface {
	mustEmbedUnimplementedUserCoreServiceServer()
}

func RegisterUserCoreServiceServer(s grpc.ServiceRegistrar, srv UserCoreServiceServer) {
	s.RegisterService(&UserCoreService_ServiceDesc, srv)
}

func _UserCoreService_PackItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackItemsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCoreServiceServer).PackItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jlu_cow_studio.pack.UserCoreService/PackItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCoreServiceServer).PackItems(ctx, req.(*PackItemsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserCoreService_ServiceDesc is the grpc.ServiceDesc for UserCoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserCoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jlu_cow_studio.pack.UserCoreService",
	HandlerType: (*UserCoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PackItems",
			Handler:    _UserCoreService_PackItems_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pack.proto",
}
